services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
    stdin_open: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    image: ingestion
    container_name: ingestion
    ports:
      - "8001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
  webchecked:
    image: check
    container_name: check
    ports:
      - "8002:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
  webmake:
    image: make
    container_name: make
    ports:
      - "8003:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
  webnotify:
    image: notify
    container_name: notify
    ports:
      - "8004:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
