services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: "no"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    image: ingestion
    container_name: ingestion
    ports:
      - "8001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
  webchecked:
    image: check
    container_name: check
    ports:
      - "8002:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
